### ISSUE TITLE
CPU mining bogs down (hashrate falls toward 0 over time)

### ISSUE THREAD

**Issue by meowsbits** [etclabscore/core-geth#14]
Migrated from: https://github.com/etclabscore/multi-geth-fork/issues/119
Original author: @meowsbits

---

I start mining. `miner.getHashrate()` is between, oh, 50000 and 70000. A week goes by, and I find hashrate down barely scraping 1000 if not 0. 

I have somewhat limited logs, due in part to limited patience and in part to journalctl rotation limits, but here's a kind of "upside down" log of the issue. You can see the "end of week" section on _top_. Then, I restart the client, restart mining, and those logs are underneath. You can see the difference of `attempts` in general.

```js
> miner.getHashrate()
68646
> miner.getHashrate()
70113

# 1 week later...
> miner.getHashrate()
203
> miner.getHashrate()
158
> 
```

```
root@hostess:~/go/src/github.com/ethereum/go-ethereum# journalctl -u multigeth_ethereumclassic_mordor.service --since '1 week ago' | grep attempts | gr
ep -v too |& tee miner_attempts.log                                                                                                                       
Jan 09 17:17:02 sf-etclabs sh[10933]: TRACE[01-09|17:17:02.540] Ethash nonce search aborted              miner=0 attempts=422                             
Jan 09 17:17:02 sf-etclabs sh[10933]: TRACE[01-09|17:17:02.571] Ethash nonce search aborted              miner=1 attempts=413                             
Jan 09 17:17:06 sf-etclabs sh[10933]: TRACE[01-09|17:17:06.618] Ethash nonce search aborted              miner=1 attempts=160                             Jan 09 17:17:06 sf-etclabs sh[10933]: TRACE[01-09|17:17:06.618] Ethash nonce search aborted              miner=0 attempts=155                             
Jan 09 17:17:15 sf-etclabs sh[10933]: TRACE[01-09|17:17:15.746] Ethash nonce search aborted              miner=1 attempts=418                             
Jan 09 17:17:15 sf-etclabs sh[10933]: TRACE[01-09|17:17:15.763] Ethash nonce search aborted              miner=0 attempts=452                             
Jan 09 17:17:17 sf-etclabs sh[10933]: TRACE[01-09|17:17:17.236] Ethash nonce search aborted              miner=1 attempts=77                              
Jan 09 17:17:17 sf-etclabs sh[10933]: TRACE[01-09|17:17:17.258] Ethash nonce search aborted              miner=0 attempts=73                              
Jan 09 17:17:43 sf-etclabs sh[10933]: TRACE[01-09|17:17:43.282] Ethash nonce search aborted              miner=1 attempts=1425                            
Jan 09 17:17:43 sf-etclabs sh[10933]: TRACE[01-09|17:17:43.305] Ethash nonce search aborted              miner=0 attempts=1439                            
Jan 09 17:17:44 sf-etclabs sh[10933]: TRACE[01-09|17:17:44.372] Ethash nonce search aborted              miner=0 attempts=52                              
Jan 09 17:17:44 sf-etclabs sh[10933]: TRACE[01-09|17:17:44.373] Ethash nonce search aborted              miner=1 attempts=56                              
Jan 09 17:17:51 sf-etclabs sh[10933]: TRACE[01-09|17:17:51.341] Ethash nonce search aborted              miner=0 attempts=344                             
Jan 09 17:17:51 sf-etclabs sh[10933]: TRACE[01-09|17:17:51.361] Ethash nonce search aborted              miner=1 attempts=324                             Jan 09 17:18:40 sf-etclabs sh[15162]: TRACE[01-09|17:18:40.001] Ethash nonce search aborted              miner=0 attempts=280407                          
Jan 09 17:18:40 sf-etclabs sh[15162]: TRACE[01-09|17:18:40.035] Ethash nonce search aborted              miner=1 attempts=276196                          
Jan 09 17:18:42 sf-etclabs sh[15162]: TRACE[01-09|17:18:42.033] Ethash nonce search aborted              miner=1 attempts=30256                           
Jan 09 17:18:42 sf-etclabs sh[15162]: TRACE[01-09|17:18:42.033] Ethash nonce search aborted              miner=0 attempts=33134                           
Jan 09 17:18:42 sf-etclabs sh[15162]: TRACE[01-09|17:18:42.250] Ethash nonce found and reported          miner=1 attempts=3854   nonce=5241881277459086967Jan 09 17:18:42 sf-etclabs sh[15162]: TRACE[01-09|17:18:42.251] Ethash nonce search aborted              miner=0 attempts=3860                            
Jan 09 17:18:45 sf-etclabs sh[15162]: TRACE[01-09|17:18:45.927] Ethash nonce search aborted              miner=1 attempts=56553                           
Jan 09 17:18:45 sf-etclabs sh[15162]: TRACE[01-09|17:18:45.927] Ethash nonce search aborted              miner=0 attempts=54616                           
Jan 09 17:18:48 sf-etclabs sh[15162]: TRACE[01-09|17:18:48.694] Ethash nonce search aborted              miner=1 attempts=44928                           
Jan 09 17:18:48 sf-etclabs sh[15162]: TRACE[01-09|17:18:48.710] Ethash nonce search aborted              miner=0 attempts=42226                           
Jan 09 17:18:55 sf-etclabs sh[15162]: TRACE[01-09|17:18:55.990] Ethash nonce search aborted              miner=1 attempts=111029                          
Jan 09 17:18:56 sf-etclabs sh[15162]: TRACE[01-09|17:18:56.002] Ethash nonce search aborted              miner=0 attempts=108714                          Jan 09 17:18:56 sf-etclabs sh[15162]: TRACE[01-09|17:18:56.680] Ethash nonce search aborted              miner=0 attempts=9924                            
Jan 09 17:18:56 sf-etclabs sh[15162]: TRACE[01-09|17:18:56.680] Ethash nonce search aborted              miner=1 attempts=11570                           
Jan 09 17:18:57 sf-etclabs sh[15162]: TRACE[01-09|17:18:57.792] Ethash nonce search aborted              miner=0 attempts=17366                           
Jan 09 17:18:57 sf-etclabs sh[15162]: TRACE[01-09|17:18:57.807] Ethash nonce search aborted              miner=1 attempts=17574                           
Jan 09 17:19:02 sf-etclabs sh[15162]: TRACE[01-09|17:19:02.899] Ethash nonce search aborted              miner=1 attempts=70371                           
Jan 09 17:19:02 sf-etclabs sh[15162]: TRACE[01-09|17:19:02.899] Ethash nonce search aborted              miner=0 attempts=65415                           
Jan 09 17:19:03 sf-etclabs sh[15162]: TRACE[01-09|17:19:03.695] Ethash nonce found and reported          miner=0 attempts=10907  nonce=5081695854271724204
Jan 09 17:19:03 sf-etclabs sh[15162]: TRACE[01-09|17:19:03.696] Ethash nonce search aborted              miner=1 attempts=11070                           
Jan 09 17:19:05 sf-etclabs sh[15162]: TRACE[01-09|17:19:05.824] Ethash nonce found and reported          miner=0 attempts=31661  nonce=8405810286462023217Jan 09 17:19:05 sf-etclabs sh[15162]: TRACE[01-09|17:19:05.825] Ethash nonce search aborted              miner=1 attempts=35346                           
Jan 09 17:19:15 sf-etclabs sh[15162]: TRACE[01-09|17:19:15.592] Ethash nonce found and reported          miner=0 attempts=158761 nonce=8407955903244848098
Jan 09 17:19:15 sf-etclabs sh[15162]: TRACE[01-09|17:19:15.599] Ethash nonce search aborted              miner=1 attempts=158142                          Jan 09 17:19:24 sf-etclabs sh[15162]: TRACE[01-09|17:19:24.768] Ethash nonce search aborted              miner=1 attempts=141533                          
Jan 09 17:19:24 sf-etclabs sh[15162]: TRACE[01-09|17:19:24.770] Ethash nonce search aborted              miner=0 attempts=141219                          
Jan 09 17:19:35 sf-etclabs sh[15162]: TRACE[01-09|17:19:35.577] Ethash nonce search aborted              miner=0 attempts=166616                          
Jan 09 17:19:35 sf-etclabs sh[15162]: TRACE[01-09|17:19:35.613] Ethash nonce search aborted              miner=1 attempts=174460                          
Jan 09 17:19:41 sf-etclabs sh[15162]: TRACE[01-09|17:19:41.245] Ethash nonce search aborted              miner=0 attempts=91526                           Jan 09 17:19:41 sf-etclabs sh[15162]: TRACE[01-09|17:19:41.245] Ethash nonce search aborted              miner=1 attempts=89261                           
Jan 09 17:19:48 sf-etclabs sh[15162]: TRACE[01-09|17:19:48.819] Ethash nonce found and reported          miner=1 attempts=123166 nonce=6322267920637101883
Jan 09 17:19:48 sf-etclabs sh[15162]: TRACE[01-09|17:19:48.819] Ethash nonce search aborted              miner=0 attempts=119838                          
Jan 09 17:20:32 sf-etclabs sh[15162]: TRACE[01-09|17:20:32.984] Ethash nonce found and reported          miner=0 attempts=689656 nonce=3789431768198540595
Jan 09 17:20:32 sf-etclabs sh[15162]: TRACE[01-09|17:20:32.990] Ethash nonce search aborted              miner=1 attempts=695456                          Jan 09 17:20:34 sf-etclabs sh[15162]: TRACE[01-09|17:20:34.960] Ethash nonce search aborted              miner=0 attempts=30422                           
Jan 09 17:20:34 sf-etclabs sh[15162]: TRACE[01-09|17:20:34.999] Ethash nonce search aborted              miner=1 attempts=28477                           
Jan 09 17:20:39 sf-etclabs sh[15162]: TRACE[01-09|17:20:39.468] Ethash nonce search aborted              miner=1 attempts=69885                           Jan 09 17:20:39 sf-etclabs sh[15162]: TRACE[01-09|17:20:39.513] Ethash nonce search aborted              miner=0 attempts=68418                           
Jan 09 17:20:40 sf-etclabs sh[15162]: TRACE[01-09|17:20:40.030] Ethash nonce search aborted              miner=0 attempts=8803                            
Jan 09 17:20:40 sf-etclabs sh[15162]: TRACE[01-09|17:20:40.030] Ethash nonce search aborted              miner=1 attempts=8575                            
Jan 09 17:20:44 sf-etclabs sh[15162]: TRACE[01-09|17:20:44.002] Ethash nonce search aborted              miner=0 attempts=60810                           
Jan 09 17:20:44 sf-etclabs sh[15162]: TRACE[01-09|17:20:44.002] Ethash nonce search aborted              miner=1 attempts=62729                           
Jan 09 17:20:49 sf-etclabs sh[15162]: TRACE[01-09|17:20:49.376] Ethash nonce search aborted              miner=1 attempts=87559                           
Jan 09 17:20:49 sf-etclabs sh[15162]: TRACE[01-09|17:20:49.376] Ethash nonce search aborted              miner=0 attempts=85580                           Jan 09 17:21:06 sf-etclabs sh[15162]: TRACE[01-09|17:21:06.711] Ethash nonce search aborted              miner=0 attempts=260419                          
Jan 09 17:21:06 sf-etclabs sh[15162]: TRACE[01-09|17:21:06.711] Ethash nonce search aborted              miner=1 attempts=267318                          
Jan 09 17:21:18 sf-etclabs sh[15162]: TRACE[01-09|17:21:18.716] Ethash nonce search aborted              miner=0 attempts=195479                          
Jan 09 17:21:18 sf-etclabs sh[15162]: TRACE[01-09|17:21:18.716] Ethash nonce search aborted              miner=1 attempts=186745     
```

**Comment by meowsbits** [comment]
```
> console.log(Date(), eth.syncing, admin.peers.length, eth.mining, eth.getHashrate(), miner.getHashrate());                                              
Mon, 02 Mar 2020 20:47:14 UTC false 5 true undefined 58534
undefined
> console.log(Date(), eth.syncing, admin.peers.length, eth.mining, eth.getHashrate(), miner.getHashrate());                                              
Mon, 02 Mar 2020 20:47:30 UTC false 4 true undefined 58006
undefined
> console.log(Date(), eth.syncing, admin.peers.length, eth.mining, eth.getHashrate(), miner.getHashrate());                                              
Mon, 02 Mar 2020 20:48:13 UTC false 5 true undefined 62082
undefined
> console.log(Date(), eth.syncing, admin.peers.length, eth.mining, eth.getHashrate(), miner.getHashrate());                                              
Mon, 02 Mar 2020 20:48:25 UTC false 6 true undefined 62250
undefined
> console.log(Date(), eth.syncing, admin.peers.length, eth.mining, eth.getHashrate(), miner.getHashrate());                                              
Wed, 04 Mar 2020 12:15:48 UTC false 12 true undefined 46317
undefined
> console.log(Date(), eth.syncing, admin.peers.length, eth.mining, eth.getHashrate(), miner.getHashrate());                                              
Wed, 04 Mar 2020 12:16:23 UTC false 12 true undefined 37617
undefined
> console.log(Date(), eth.syncing, admin.peers.length, eth.mining, eth.getHashrate(), miner.getHashrate());                                              
Wed, 04 Mar 2020 12:16:52 UTC false 13 true undefined 42222
undefined
> console.log(Date(), eth.syncing, admin.peers.length, eth.mining, eth.getHashrate(), miner.getHashrate());                                              
Fri, 06 Mar 2020 13:50:10 UTC false 18 true undefined 87
undefined
> console.log(Date(), eth.syncing, admin.peers.length, eth.mining, eth.getHashrate(), miner.getHashrate());                                              
Fri, 06 Mar 2020 13:50:12 UTC false 18 true undefined 87
undefined
> miner.stop();
null
> miner.start(2);
null
> miner.start(2);
Error: write unix @->/root/go/src/github.com/ethereum/go-ethereum/multigeth_ethereumclassic_mordor.ipc: use of closed network connection                 
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1

> miner.start(2);
null
> console.log(Date(), eth.syncing, admin.peers.length, eth.mining, eth.getHashrate(), miner.getHashrate());                                              
Fri, 06 Mar 2020 14:09:19 UTC false 11 true undefined 60770
undefined
> console.log(Date(), eth.syncing, admin.peers.length, eth.mining, eth.getHashrate(), miner.getHashrate());                                              
Sat, 07 Mar 2020 15:17:25 UTC false 18 true undefined 58960
undefined
> console.log(Date(), eth.syncing, admin.peers.length, eth.mining, eth.getHashrate(), miner.getHashrate());                                              
Sat, 07 Mar 2020 15:17:28 UTC false 19 true undefined 59486
undefined
> console.log(Date(), eth.syncing, admin.peers.length, eth.mining, eth.getHashrate(), miner.getHashrate());                                              
Sat, 07 Mar 2020 15:17:39 UTC false 17 true undefined 58957
undefined
> console.log(Date(), eth.syncing, admin.peers.length, eth.mining, eth.getHashrate(), miner.getHashrate());                                              
Mon, 09 Mar 2020 13:09:19 UTC false 15 true undefined 97
undefined
> console.log(Date(), eth.syncing, admin.peers.length, eth.mining, eth.getHashrate(), miner.getHashrate());                                              
Mon, 09 Mar 2020 13:09:25 UTC false 15 true undefined 166
undefined
> miner.stop(); miner.start(2);
```

**Comment by meowsbits** [comment]
@tzdybal Here's a visual explanation of what I'm seeing on Mordor. The timeframe shown here is 5 days. 

- The first two days I was mining with just 1 CPU.
- Mining eventually degrades, at which point I restart with 2 CPUs (~ 0800 5/23)

The machine has 2 CPUs and 4GB RAM and a 4GB swapfile (it's a DO VPS).
One hypothesis is "The machine simply has too little memory and you're seeing aberrant behavior because of that." @stevanlohja has reported no issues mining Mordor on an 8GB RAM machine (also from DO).

![image](https://user-images.githubusercontent.com/45600330/82907255-fd483780-9f2b-11ea-9606-96ba1a96321f.png)

**Comment by meowsbits** [comment]
Detail shot of middle time section above:

![image](https://user-images.githubusercontent.com/45600330/83065560-4e8a2100-a029-11ea-8f7e-cf3a879ee3be.png)

**Comment by meowsbits** [comment]
And this is what it looks like when I run the miner in intervals, eg `for (;true;) { miner.start(); admin.sleep(40*60); miner.stop(); admin.sleep(20*60); }`.

![image](https://user-images.githubusercontent.com/45600330/83081648-c4e94c00-a046-11ea-8477-160cde21c85e.png)

**Comment by tzdybal** [comment]
I'm not able to reproduce the issue.
My reported hashrate is 25235.43 on average (with standard deviation of 193.24).

**Comment by meowsbits** [comment]
Can you document what you did to reproduce it (so future us can maybe try something else)?

**Comment by tzdybal** [comment]
I was running mining on single core, on my local FreeBSD machine with 8GB RAM/4GB swap, on mordor, for about a week. Node is synced with `--syncmode full --gcmode archive`. `go version go1.13.5 freebsd/amd64`
I was also trying to reproduce it by mining (various core counts) on my laptop - with no visible issues after few days. `go version go1.14.3 linux/amd64`

**Comment by meowsbits** [comment]
I suppose I should have documented my _producing_ environment as well. 

 Linux, 4GB RAM, 4GB swap, go1.13.5, saw behavior mining on both 2 and 1 cores.

**Comment by meowsbits** [comment]
Just touching with an update; this is still an issue for me.

Seeing on Mordor, where for the last 48 hours or so, my node has been the only miner. 

```
"CoreGeth/v1.11.23-unstable-b75e05cb-20210223/linux-amd64/go1.15.5"
```
![2021-02-24-053446_1448x337_screenshot](https://user-images.githubusercontent.com/45600330/108997228-f2f6cd80-7664-11eb-81d0-d6fb9015f450.png)
![2021-02-24-053438_712x354_screenshot](https://user-images.githubusercontent.com/45600330/108997242-f722eb00-7664-11eb-83d0-7a759d436f6f.png)
![2021-02-24-054004_2185x911_screenshot](https://user-images.githubusercontent.com/45600330/108997272-0013bc80-7665-11eb-8e36-9dee5f452700.png)

**Comment by meowsbits** [comment]
... and restarted geth (about 0545 clock time):

![image](https://user-images.githubusercontent.com/45600330/109079355-74317d00-76c4-11eb-95f2-74895d9e5e85.png)

**Comment by meowsbits** [comment]
```
> console.log(Date(), "hashrate=", eth.hashrate, "peers=", admin.peers.length, "block.#=", eth.blockNumber);
Tue May 25 2021 21:35:12 GMT+0000 (UTC) hashrate= 30875 peers= 31 block.#= 3945719
null
> console.log(Date(), "hashrate=", eth.hashrate, "peers=", admin.peers.length, "block.#=", eth.blockNumber);
Wed May 26 2021 11:10:24 GMT+0000 (UTC) hashrate= 30542 peers= 36 block.#= 3949803
null
> console.log(Date(), "hashrate=", eth.hashrate, "peers=", admin.peers.length, "block.#=", eth.blockNumber);
Thu May 27 2021 13:40:06 GMT+0000 (UTC) hashrate= 28831 peers= 35 block.#= 3957182
null
> console.log(Date(), "hashrate=", eth.hashrate, "peers=", admin.peers.length, "block.#=", eth.blockNumber);
Thu May 27 2021 21:43:36 GMT+0000 (UTC) hashrate= 30147 peers= 37 block.#= 3959750
null
> console.log(Date(), "hashrate=", eth.hashrate, "peers=", admin.peers.length, "block.#=", eth.blockNumber);
Mon May 31 2021 12:49:24 GMT+0000 (UTC) hashrate= 29732 peers= 39 block.#= 3983992
null
> console.log(Date(), "hashrate=", eth.hashrate, "peers=", admin.peers.length, "block.#=", eth.blockNumber);
Tue Jun 01 2021 16:15:26 GMT+0000 (UTC) hashrate= 25990 peers= 7 block.#= 3989973
null                                                                                     
> console.log(Date(), "hashrate=", eth.hashrate, "peers=", admin.peers.length, "block.#=", eth.blockNumber);
Tue Jun 01 2021 16:18:32 GMT+0000 (UTC) hashrate= 28820 peers= 7 block.#= 3989978
null
> console.log(Date(), "hashrate=", eth.hashrate, "peers=", admin.peers.length, "block.#=", eth.blockNumber);
Tue Jun 01 2021 16:19:30 GMT+0000 (UTC) hashrate= 29206 peers= 7 block.#= 3989978
null
> console.log(Date(), "hashrate=", eth.hashrate, "peers=", admin.peers.length, "block.#=", eth.blockNumber);
Tue Jul 13 2021 12:27:34 GMT+0000 (UTC) hashrate= 918 peers= 16 block.#= 4272333
null
> console.log(Date(), "hashrate=", eth.hashrate, "peers=", admin.peers.length, "block.#=", eth.blockNumber);
Tue Jul 13 2021 12:27:44 GMT+0000 (UTC) hashrate= 777 peers= 16 block.#= 4272333

```

**Comment by meowsbits** [comment]
```sh
# ./build/bin/geth version
CoreGeth
Version: 1.12.7-unstable
Git Commit: 9090b5ee2e92fa06932289611c35338bda5a1cbc
Git Commit Date: 20220405
Architecture: amd64
Go Version: go1.16
Operating System: linux
GOPATH=/root/go
GOROOT=/usr/local/go
```

```js
> console.log(Date(), "hashrate=", eth.hashrate, "peers=", admin.peers.length, "block.#=", eth.blockNumber, "version=", admin.nodeInfo.name, eth.mining, JSON.stringify(eth.syncing));
Mon Apr 11 2022 15:10:22 GMT+0000 (UTC) hashrate= 0 peers= 3 block.#= 6117016 version= CoreGeth/v1.12.7-unstable-9090b5ee-20220405/linux-amd64/go1.16 true false
null
> console.log(Date(), "hashrate=", eth.hashrate, "peers=", admin.peers.length, "block.#=", eth.blockNumber, "version=", admin.nodeInfo.name, eth.mining, JSON.stringify(eth.syncing));
Mon Apr 11 2022 17:49:37 GMT+0000 (UTC) hashrate= 0 peers= 3 block.#= 6117661 version= CoreGeth/v1.12.7-unstable-9090b5ee-20220405/linux-amd64/go1.16 true false
null
> miner.stop()
null
> miner.start(1)
null
> console.log(Date(), "hashrate=", eth.hashrate, "peers=", admin.peers.length, "block.#=", eth.blockNumber, "version=", admin.nodeInfo.name, eth.mining, JSON.stringify(eth.syncing));
Mon Apr 11 2022 17:49:55 GMT+0000 (UTC) hashrate= 0 peers= 3 block.#= 6117663 version= CoreGeth/v1.12.7-unstable-9090b5ee-20220405/linux-amd64/go1.16 true false
null
> console.log(Date(), "hashrate=", eth.hashrate, "peers=", admin.peers.length, "block.#=", eth.blockNumber, "version=", admin.nodeInfo.name, eth.mining, JSON.stringify(eth.syncing));                                                        
Wed Apr 13 2022 13:52:55 GMT+0000 (UTC) hashrate= 0 peers= 15 block.#= 6130335 version= CoreGeth/v1.12.7-unstable-9090b5ee-20220405/linux-amd64/go1.16 true false                                                                             
null
> miner.stop()
null
> miner.start(1)
null
> console.log(Date(), "hashrate=", eth.hashrate, "peers=", admin.peers.length, "block.#=", eth.blockNumber, "version=", admin.nodeInfo.name, eth.mining, JSON.stringify(eth.syncing));                                                        
Wed Apr 13 2022 13:54:11 GMT+0000 (UTC) hashrate= 0 peers= 15 block.#= 6130341 version= CoreGeth/v1.12.7-unstable-9090b5ee-20220405/linux-amd64/go1.16 true false                                                                             
null
> miner.getHashrate()
Error: the method miner_getHashrate does not exist/is not available
        at web3.js:6365:37(47)
        at send (web3.js:5099:62(35))
        at <eval>:1:18(3)

> miner
{
  getHashrate: function(),
  setEtherbase: function(),
  setExtra: function(),
  setGasLimit: function(),
  setGasPrice: function(),
  setRecommitInterval: function(),
  start: function(),
  stop: function()
}
> miner.getHashrate();
Error: the method miner_getHashrate does not exist/is not available
        at web3.js:6365:37(47)
        at send (web3.js:5099:62(35))
        at <eval>:1:18(3)

> eth.hashrate
0
> eth.mining
true

```

**Comment by ziogaschr** [comment]
Can it be that DO doesn't like mining and long running tasks and they have a system in place that limits process resources?

Will give it a try at linode.

**Comment by meowsbits** [comment]
I'm in GMT-7; bog down event at 2200 local time, 0500 GMT-0.
```
> admin.nodeInfo.name
"CoreGeth/v1.12.9-unstable-cd1f5160-20220901/linux-amd64/go1.16"
```
![image](https://user-images.githubusercontent.com/45600330/188029297-6fd228ed-53fb-4828-adba-e327c7b84bf1.png)
![image](https://user-images.githubusercontent.com/45600330/188029339-1d4c385b-8b93-40cb-b470-e12c607b249e.png)

**Comment by meowsbits** [comment]
I wonder if its correlated with a DAG file generation or something like that.

**Comment by meowsbits** [comment]
![image](https://user-images.githubusercontent.com/45600330/188156996-d8406808-5f84-4e9c-b33d-cf83b9ecefdd.png)
![image](https://user-images.githubusercontent.com/45600330/188159362-7b09509b-4b9f-4b5f-9def-9e09b58baadd.png)
