### ISSUE TITLE
geth copydb command fails

### ISSUE THREAD

**Issue by meowsbits** [etclabscore/core-geth#222]
#### System information

```
> ./build/bin/geth version
CoreGeth
Version: 1.11.17-unstable
Git Commit: e447981171d6dd46e9f893a8f679d645ce56604b
Git Commit Date: 20201105
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15
Operating System: linux
GOPATH=/home/ia/go
GOROOT=/home/ia/go1.15.linux-amd64
```

#### Expected behaviour

`geth copydb` copies a database successfully or logs a sensible error rationalizing its refusal and exits.

#### Actual behaviour

1. Case when source db does not contain block data (no import progress). Program logs `retrieved ancestor is invalid` and exits `1`. Target database does not exist.

2. Case when source db _does_ contain block data (some import progress). Program panics. This appears to be an issue with ancient/kv relationship. It is expected that the imported historical data should have gone straight to ancient, and the KV should be essentially empty.

#### Steps to reproduce the behaviour

__Case 1__

```
> ./build/bin/geth --datadir ./dd --exec 'exit;' console

[...]

> [[ -d ./dd/geth/chaindata ]] && echo ok
ok

> ./build/bin/geth copydb ./dd/geth/chaindata /tmp/geth_dd_copy
INFO [11-05|09:59:13.397] Maximum peer count                       ETH=50 LES=0 total=50
INFO [11-05|09:59:13.397] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [11-05|09:59:13.399] Set global gas cap                       cap=25000000
INFO [11-05|09:59:13.399] Allocated cache and file handles         database=/home/ia/.ethereum/geth/chaindata cache=512.00MiB handles=524288
INFO [11-05|09:59:13.449] Opened ancient database                  database=/home/ia/.ethereum/geth/chaindata/ancient
INFO [11-05|09:59:13.454] Found stored genesis block               config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 ConstantinopleFix: 7280000 Istanbul: 9069000 MuirGlacier: 9200000 Engine: ethash}"
INFO [11-05|09:59:13.458] Disk storage enabled for ethash caches   dir=/home/ia/.ethereum/geth/ethash count=3
INFO [11-05|09:59:13.458] Disk storage enabled for ethash DAGs     dir=/home/ia/.ethash               count=2
INFO [11-05|09:59:13.461] Loaded most recent local header          number=2451749 hash="b2bc1b…fc82fe" td=75809384211441016928 age=4y1mo1w
INFO [11-05|09:59:13.461] Loaded most recent local full block      number=0       hash="d4e567…cb8fa3" td=17179869184          age=51y7mo1d
INFO [11-05|09:59:13.461] Loaded most recent local fast block      number=2451749 hash="b2bc1b…fc82fe" td=75809384211441016928 age=4y1mo1w
INFO [11-05|09:59:13.461] Loaded last fast-sync pivot marker       number=11180265
INFO [11-05|09:59:13.488] Allocated fast sync bloom                size=512.00MiB
INFO [11-05|09:59:13.489] Allocated cache and file handles         database=./dd/geth/chaindata               cache=512.00MiB handles=256
INFO [11-05|09:59:13.559] Opened ancient database                  database=/tmp/geth_dd_copy
INFO [11-05|09:59:13.560] Block synchronisation started 
WARN [11-05|09:59:13.560] Ancestor below allowance                 peer=local number=2361749  hash="000000…000000" allowance=2361749
WARN [11-05|09:59:13.560] Synchronisation failed, dropping peer    peer=local err="retrieved ancestor is invalid"
WARN [11-05|09:59:13.560] Downloader wants to drop peer, but peerdrop-function is not set peer=local
INFO [11-05|09:59:13.588] Initialized fast sync bloom              items=84547 errorrate=0.000 elapsed=99.664ms
retrieved ancestor is invalid

> echo $?
1

```

__Case 2__

```
> ./build/bin/geth copydb ./dd/geth/chaindata /tmp/geth_dd_copy
INFO [11-05|10:02:53.337] Maximum peer count                       ETH=50 LES=0 total=50
INFO [11-05|10:02:53.337] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [11-05|10:02:53.339] Set global gas cap                       cap=25000000
INFO [11-05|10:02:53.339] Allocated cache and file handles         database=/home/ia/.ethereum/geth/chaindata cache=512.00MiB handles=524288
INFO [11-05|10:02:53.382] Opened ancient database                  database=/home/ia/.ethereum/geth/chaindata/ancient
INFO [11-05|10:02:53.386] Found stored genesis block               config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 ConstantinopleFix: 7280000 Istanbul: 9069000 MuirGlacier: 9200000 Engine: ethash}"
INFO [11-05|10:02:53.388] Disk storage enabled for ethash caches   dir=/home/ia/.ethereum/geth/ethash count=3
INFO [11-05|10:02:53.388] Disk storage enabled for ethash DAGs     dir=/home/ia/.ethash               count=2
INFO [11-05|10:02:53.390] Loaded most recent local header          number=2451749 hash="b2bc1b…fc82fe" td=75809384211441016928 age=4y1mo1w
INFO [11-05|10:02:53.390] Loaded most recent local full block      number=0       hash="d4e567…cb8fa3" td=17179869184          age=51y7mo1d
INFO [11-05|10:02:53.390] Loaded most recent local fast block      number=2451749 hash="b2bc1b…fc82fe" td=75809384211441016928 age=4y1mo1w
INFO [11-05|10:02:53.390] Loaded last fast-sync pivot marker       number=11180265
INFO [11-05|10:02:53.413] Allocated fast sync bloom                size=512.00MiB
INFO [11-05|10:02:53.414] Allocated cache and file handles         database=./dd/geth/chaindata               cache=512.00MiB handles=256
INFO [11-05|10:02:53.455] Opened ancient database                  database=/tmp/geth_dd_copy
WARN [11-05|10:02:53.455] Freezer/KV validation error, attempting freezer repair error="ancient chain segments already extracted, please set --datadir.ancient to the correct path"
WARN [11-05|10:02:53.455] Freezer repair OK 
INFO [11-05|10:02:53.459] Initialized fast sync bloom              items=4757 errorrate=0.000 elapsed=45.854ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x92674f]

goroutine 1 [running]:
github.com/ethereum/go-ethereum/core/rawdb.truncateKVtoFreezer(0xc0005a41e0, 0x15e88c0, 0xc000222200)
        github.com/ethereum/go-ethereum/core/rawdb/database.go:572 +0xef
github.com/ethereum/go-ethereum/core/rawdb.NewDatabaseWithFreezer(0x15e88c0, 0xc000222200, 0x7ffcbff4dd3e, 0x11, 0x0, 0x0, 0xc000222200, 0x0, 0x0, 0x1379c01)
        github.com/ethereum/go-ethereum/core/rawdb/database.go:254 +0x38d
github.com/ethereum/go-ethereum/core/rawdb.NewLevelDBDatabaseWithFreezer(0x7ffcbff4dd2a, 0x13, 0x200, 0x100, 0x7ffcbff4dd3e, 0x11, 0x0, 0x0, 0xc0000d6580, 0x0, ...)
        github.com/ethereum/go-ethereum/core/rawdb/database.go:328 +0xd7
main.copyDb(0xc0000f6580, 0x0, 0x0)
        github.com/ethereum/go-ethereum/cmd/geth/chaincmd.go:482 +0x2c6
github.com/ethereum/go-ethereum/cmd/utils.MigrateFlags.func1(0xc0000f6580, 0x0, 0xc0000f6580)
        github.com/ethereum/go-ethereum/cmd/utils/flags.go:2073 +0xbe
gopkg.in/urfave/cli%2ev1.HandleAction(0x1199f40, 0xc00020afe0, 0xc0000f6580, 0xc000372300, 0x0)
        gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0x82
gopkg.in/urfave/cli%2ev1.Command.Run(0x137b04e, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x13b5c8e, 0x33, 0x0, ...)
        gopkg.in/urfave/cli.v1@v1.20.0/command.go:210 +0x9fb
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0002189c0, 0xc000032080, 0x4, 0x4, 0x0, 0x0)
        gopkg.in/urfave/cli.v1@v1.20.0/app.go:255 +0x768
main.main()
        github.com/ethereum/go-ethereum/cmd/geth/main.go:288 +0x55
```

**Comment by meowsbits** [comment]
I was using the `geth copydb` command wrong. See https://github.com/etclabscore/core-geth/issues/222. 

I swear it used be `geth copydb <source> <target>`... oh well.
