### ISSUE TITLE
runtime: unexpected return pc for runtime.systemstack_switch

### ISSUE THREAD

**Issue by meowsbits** [etclabscore/core-geth#349]
This was a strange and unreproducable error I encountered.

#### System information

```
./build/bin/geth version
CoreGeth
Version: 1.11.23-unstable
Git Commit: 91a2abdd144c8fb89ddd3ee9a401ea7158b850d2
Git Commit Date: 20210323
Architecture: amd64
Go Version: go1.16.2
Operating System: linux
GOPATH=/home/ia/go
GOROOT=/home/ia/go1.16.2.linux-amd64
```

Commit hash : 91a2abdd144c8fb89ddd3ee9a401ea7158b850d2

#### Backtrace

````
go test ./...
?       github.com/ethereum/go-ethereum [no test files]
ok      github.com/ethereum/go-ethereum/accounts        (cached)
ok      github.com/ethereum/go-ethereum/accounts/abi    (cached)
# github.com/ethereum/go-ethereum/crypto/bls12381
runtime: unexpected return pc for runtime.systemstack_switch called from 0x19c079de9c82b42d
stack: frame={sp:0xc000114f78, fp:0xc000114f80} stack=[0xc000112000,0xc000116000)
000000c000114e78:  0000000000000000  0000000000000000
000000c000114e88:  0000000000000000  0000000000000000
000000c000114e98:  0000000000000000  0000000000000000
000000c000114ea8:  0000000000000000  0000000000000000
000000c000114eb8:  0000000000000000  0000000000000000
000000c000114ec8:  0000000000000000  0000000000000000
000000c000114ed8:  0000000000000000  0000000000000000
000000c000114ee8:  0000000000000000  0000000000000000
000000c000114ef8:  0000000000000000  0000000000000000
000000c000114f08:  0000000000000000  0000000000000000
000000c000114f18:  0000000000000000  0000000000000000
000000c000114f28:  0000000000000000  0000000000000000
000000c000114f38:  0000000000000000  0000000000000000
000000c000114f48:  0000000000000000  0000000000000000
000000c000114f58:  0000000000000000  0000000000000000
000000c000114f68:  0000000000000000  0000000000000000
000000c000114f78: <19c079de9c82b42d >1ec69448926c4610
000000c000114f88:  0000000000000000  0000000000000000
000000c000114f98:  0000000000000000  3f847ae147ae147b
000000c000114fa8:  0000000000000000  0000000000000000
000000c000114fb8:  0000000000000000  40c3880000000000
000000c000114fc8:  0000000000000000  0000000000000000
000000c000114fd8:  0000000000000000  416312d000000000
000000c000114fe8:  0000000000000000  0000000000000000
000000c000114ff8:  0000000000000000  0000000000000010
000000c000115008:  0000000000000000  0000000000000020
000000c000115018:  00007f3b9bc93108  0000000000000020
000000c000115028:  000000c000143088  0000000000029c1a
000000c000115038:  000000c000143088  000000000055af05 <go/parser.(*parser).expectClosing+101>
000000c000115048:  000000c000217500  000000c000000180
000000c000115058:  000000c000143088  000000000040ddd8 <runtime.newobject+56>
000000c000115068:  0000000000000040  00000000006dc6c0
000000c000115078:  0000000000000001
fatal error: unknown caller pc

runtime stack:
runtime.throw(0x701f82, 0x11)
        /usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.gentraceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc000000180, 0x0, 0x0, 0x7fffffff, 0x7133f0, 0xc00006faf8, 0x0, ...)
        /usr/local/go/src/runtime/traceback.go:261 +0x1a56
runtime.copystack(0xc000000180, 0x4000)
        /usr/local/go/src/runtime/stack.go:908 +0x2f1
runtime.shrinkstack(0xc000000180)
        /usr/local/go/src/runtime/stack.go:1180 +0x13d
runtime.scanstack(0xc000000180, 0xc00003e698)
        /usr/local/go/src/runtime/mgcmark.go:720 +0x58e
runtime.markroot.func1()
        /usr/local/go/src/runtime/mgcmark.go:233 +0xc6
runtime.markroot(0xc00003e698, 0x14)
        /usr/local/go/src/runtime/mgcmark.go:206 +0x33e
runtime.gcDrain(0xc00003e698, 0x7)
        /usr/local/go/src/runtime/mgcmark.go:1014 +0x118
runtime.gcBgMarkWorker.func2()
        /usr/local/go/src/runtime/mgc.go:2003 +0x17e
runtime.systemstack(0x0)
        /usr/local/go/src/runtime/asm_amd64.s:379 +0x66
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1246

goroutine 16 [GC worker (idle)]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:339 fp=0xc000059760 sp=0xc000059758 pc=0x467660
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1967 +0x1c7 fp=0xc0000597e0 sp=0xc000059760 pc=0x41d127
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0000597e8 sp=0xc0000597e0 pc=0x469361
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1835 +0x37

goroutine 1 [GC assist marking (scan)]:
runtime: unexpected return pc for runtime.systemstack_switch called from 0x19c079de9c82b42d
stack: frame={sp:0xc000114f78, fp:0xc000114f80} stack=[0xc000112000,0xc000116000)
000000c000114e78:  0000000000000000  0000000000000000
000000c000114e88:  0000000000000000  0000000000000000
000000c000114e98:  0000000000000000  0000000000000000
000000c000114ea8:  0000000000000000  0000000000000000
000000c000114eb8:  0000000000000000  0000000000000000
000000c000114ec8:  0000000000000000  0000000000000000
000000c000114ed8:  0000000000000000  0000000000000000
000000c000114ee8:  0000000000000000  0000000000000000
000000c000114ef8:  0000000000000000  0000000000000000
000000c000114f08:  0000000000000000  0000000000000000
000000c000114f18:  0000000000000000  0000000000000000
000000c000114ef8:  0000000000000000  0000000000000000
000000c000114f08:  0000000000000000  0000000000000000
000000c000114f18:  0000000000000000  0000000000000000
000000c000114f28:  0000000000000000  0000000000000000
000000c000114f38:  0000000000000000  0000000000000000
000000c000114f48:  0000000000000000  0000000000000000
000000c000114f58:  0000000000000000  0000000000000000
000000c000114f68:  0000000000000000  0000000000000000
000000c000114f78: <19c079de9c82b42d >1ec69448926c4610
000000c000114f88:  0000000000000000  0000000000000000
000000c000114f98:  0000000000000000  3f847ae147ae147b
000000c000114fa8:  0000000000000000  0000000000000000
000000c000114fb8:  0000000000000000  40c3880000000000
000000c000114fc8:  0000000000000000  0000000000000000
000000c000114fd8:  0000000000000000  416312d000000000
000000c000114fe8:  0000000000000000  0000000000000000
000000c000114ff8:  0000000000000000  0000000000000010
000000c000115008:  0000000000000000  0000000000000020
000000c000115018:  00007f3b9bc93108  0000000000000020
000000c000115028:  000000c000143088  0000000000029c1a
000000c000115038:  000000c000143088  000000000055af05 <go/parser.(*parser).expectClosing+101>
000000c000115048:  000000c000217500  000000c000000180
000000c000115058:  000000c000143088  000000000040ddd8 <runtime.newobject+56>
000000c000115068:  0000000000000040  00000000006dc6c0
000000c000115078:  0000000000000001
runtime: unexpected return pc for runtime.systemstack_switch called from 0x19c079de9c82b42d
stack: frame={sp:0xc000114f78, fp:0xc000114f80} stack=[0xc000112000,0xc000116000)
000000c000114e78:  0000000000000000  0000000000000000
000000c000114e88:  0000000000000000  0000000000000000
000000c000114e98:  0000000000000000  0000000000000000
000000c000114ea8:  0000000000000000  0000000000000000
000000c000114eb8:  0000000000000000  0000000000000000
000000c000114ec8:  0000000000000000  0000000000000000
000000c000114ed8:  0000000000000000  0000000000000000
000000c000114ee8:  0000000000000000  0000000000000000
000000c000114ef8:  0000000000000000  0000000000000000
000000c000114f08:  0000000000000000  0000000000000000
000000c000114f18:  0000000000000000  0000000000000000
000000c000114f28:  0000000000000000  0000000000000000
000000c000114f38:  0000000000000000  0000000000000000
000000c000114f48:  0000000000000000  0000000000000000
000000c000114f58:  0000000000000000  0000000000000000
000000c000114f68:  0000000000000000  0000000000000000
000000c000114f78: <19c079de9c82b42d >1ec69448926c4610
000000c000114f88:  0000000000000000  0000000000000000
000000c000114f98:  0000000000000000  3f847ae147ae147b
000000c000114fa8:  0000000000000000  0000000000000000
000000c000114fb8:  0000000000000000  40c3880000000000
000000c000114fc8:  0000000000000000  0000000000000000
000000c000114fd8:  0000000000000000  416312d000000000
000000c000114fe8:  0000000000000000  0000000000000000
000000c000114ff8:  0000000000000000  0000000000000010
000000c000115008:  0000000000000000  0000000000000020
000000c000115018:  00007f3b9bc93108  0000000000000020
000000c000115028:  000000c000143088  0000000000029c1a
000000c000115038:  000000c000143088  000000000055af05 <go/parser.(*parser).expectClosing+101>
000000c000115048:  000000c000217500  000000c000000180
000000c000115058:  000000c000143088  000000000040ddd8 <runtime.newobject+56>
000000c000115068:  0000000000000040  00000000006dc6c0
000000c000115078:  0000000000000001
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:339
ok      github.com/ethereum/go-ethereum/accounts/abi/bind       7.300s
ok      github.com/ethereum/go-ethereum/accounts/abi/bind/backends      0.250s

````

**Comment by diega** [comment]
Closing this as unreproducible, in line with your own note at the time. The crash is a Go runtime failure during stack copying, which on that vintage was usually the hand written amd64 assembly in `crypto/bls12381` interacting badly with go1.16. Nothing similar has been reported in the five years since, across many toolchain upgrades, and there is no code change here to point at as the fix. If it reappears on a current build it will be worth a fresh report with the toolchain version, since the analysis would start from a different place.
