### ISSUE TITLE
panic at les txpool reorg

### ISSUE THREAD

**Issue by meowsbits** [etclabscore/core-geth#53]
#### System information

Geth version: v1.11.0-core
OS & Version: Linux

#### Actual behaviour
```
Mar 04 12:22:51 sf-etclabs sh[26575]: WARN [03-04|12:22:51.621] Skipping faucet refresh, head too old    number=778682 hash=5a1633…3c13bf age=1mo3d16h   
Mar 04 12:22:51 sf-etclabs sh[26575]: WARN [03-04|12:22:51.622] Skipping faucet refresh, head too old    number=778683 hash=145cc7…01f163 age=1mo3d16h   
Mar 04 12:22:51 sf-etclabs sh[26575]: WARN [03-04|12:22:51.622] Skipping faucet refresh, head too old    number=778684 hash=74d573…562392 age=1mo3d16h   
Mar 04 12:22:51 sf-etclabs sh[26575]: panic: runtime error: invalid memory address or nil pointer dereference                                            
Mar 04 12:22:51 sf-etclabs sh[26575]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xc5937c]                                           
Mar 04 12:22:51 sf-etclabs sh[26575]: goroutine 57 [running]:                                                                                            
Mar 04 12:22:51 sf-etclabs sh[26575]: github.com/ethereum/go-ethereum/light.(*TxPool).reorgOnNewHead(0xc00038cc60, 0x11a2960, 0xc0204bd920, 0xc0209ec480,
0xc0204bd920, 0xc02096eb00, 0x8)                                                                                                                         
Mar 04 12:22:51 sf-etclabs sh[26575]:         /root/go/src/github.com/ethereum/go-ethereum/light/txpool.go:230 +0x23c                                    
Mar 04 12:22:51 sf-etclabs sh[26575]: github.com/ethereum/go-ethereum/light.(*TxPool).setNewHead(0xc00038cc60, 0xc0209ec480)                             
Mar 04 12:22:51 sf-etclabs sh[26575]:         /root/go/src/github.com/ethereum/go-ethereum/light/txpool.go:311 +0x13a                                    
Mar 04 12:22:51 sf-etclabs sh[26575]: github.com/ethereum/go-ethereum/light.(*TxPool).eventLoop(0xc00038cc60)                                            
Mar 04 12:22:51 sf-etclabs sh[26575]:         /root/go/src/github.com/ethereum/go-ethereum/light/txpool.go:292 +0x53                                     
Mar 04 12:22:51 sf-etclabs sh[26575]: created by github.com/ethereum/go-ethereum/light.NewTxPool                                                         
Mar 04 12:22:51 sf-etclabs sh[26575]:         /root/go/src/github.com/ethereum/go-ethereum/light/txpool.go:109 +0x3eb                                    
```

#### Steps to reproduce the behaviour

Run `faucet`, need reorg.

**Comment by meowsbits** [comment]
Seemed to resolve itself after the restart this caused, and I haven't seen it happen again.
