### ISSUE TITLE
make all: segmentation fault cmd/wnode (gcc failed)

### ISSUE THREAD

**Issue by meowsbits** [etclabscore/core-geth#73]
---
### System and Version Info
- OS: Ubuntu 18.04.3 LTS (bionic)
```
gcc version: gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1) 
go version go1.13.5 linux/amd64
node version: v13.6.0
npm version: 6.13.7
Python 3.6.8
```
---

```
git checkout v1.11.1
make all
```

```
github.com/ethereum/go-ethereum/p2p/simulations
github.com/ethereum/go-ethereum/cmd/p2psim
github.com/ethereum/go-ethereum/p2p/testing
github.com/ethereum/go-ethereum/p2p/simulations/examples
github.com/ethereum/go-ethereum/les
github.com/ethereum/go-ethereum/ethstats
github.com/ethereum/go-ethereum/mobile
github.com/ethereum/go-ethereum/cmd/faucet
github.com/ethereum/go-ethereum/cmd/utils
github.com/ethereum/go-ethereum/cmd/bootnode
github.com/ethereum/go-ethereum/cmd/abigen
github.com/ethereum/go-ethereum/cmd/checkpoint-admin
github.com/ethereum/go-ethereum/cmd/ethkey
github.com/ethereum/go-ethereum/cmd/evm
github.com/ethereum/go-ethereum/cmd/clef
github.com/ethereum/go-ethereum/cmd/geth
github.com/ethereum/go-ethereum/cmd/wnode
# github.com/ethereum/go-ethereum/cmd/wnode
unexpected fault address 0x7f90f35c3000
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7f90f35c3000 pc=0x45baea]

goroutine 1 [running]:
runtime.throw(0x690f25, 0x5)
        /usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc0007c9018 sp=0xc0007c8fe8 pc=0x42dc42
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:391 +0x455 fp=0xc0007c9048 sp=0xc0007c9018 pc=0x442be5
runtime.memmove(0x7f90f35c07f1, 0xc011bfe000, 0x3dd5)
        /usr/local/go/src/runtime/memmove_amd64.s:363 +0x42a fp=0xc0007c9050 sp=0xc0007c9048 pc=0x45baea
cmd/link/internal/ld.(*OutBuf).Write(0xc0000828c0, 0xc011bfe000, 0x3dd5, 0x5000, 0x5b, 0x0, 0x0)
        /usr/local/go/src/cmd/link/internal/ld/outbuf.go:65 +0xa0 fp=0xc0007c90a0 sp=0xc0007c9050 pc=0x5ac560
cmd/link/internal/ld.(*OutBuf).WriteSym(0xc0000828c0, 0xc00be50070)
        /usr/local/go/src/cmd/link/internal/ld/outbuf.go:159 +0x6c fp=0xc0007c90f0 sp=0xc0007c90a0 pc=0x5acd2c
cmd/link/internal/ld.blk(0xc0000828c0, 0xc012924000, 0x10a24, 0x11400, 0x1ff17f1, 0x1164db9, 0x8771e0, 0x200, 0x200)
        /usr/local/go/src/cmd/link/internal/ld/data.go:786 +0x10f fp=0xc0007c91c0 sp=0xc0007c90f0 pc=0x5599af
cmd/link/internal/ld.Dwarfblk(0xc0006d6000, 0x17f0000, 0x1164db9)
        /usr/local/go/src/cmd/link/internal/ld/data.go:899 +0xaf fp=0xc0007c9260 sp=0xc0007c91c0 pc=0x55aaef
cmd/link/internal/amd64.asmb(0xc0006d6000)
        /usr/local/go/src/cmd/link/internal/amd64/asm.go:706 +0x2f7 fp=0xc0007c92d0 sp=0xc0007c9260 pc=0x5d1e57
cmd/link/internal/ld.Main(0x84bdc0, 0x10, 0x20, 0x1, 0x7, 0x10, 0x69ac6c, 0x1b, 0x697753, 0x14, ...)
        /usr/local/go/src/cmd/link/internal/ld/main.go:262 +0xd5d fp=0xc0007c9428 sp=0xc0007c92d0 pc=0x5ab5ad
main.main()
        /usr/local/go/src/cmd/link/main.go:65 +0x1d6 fp=0xc0007c9f60 sp=0xc0007c9428 pc=0x614616
runtime.main()
        /usr/local/go/src/runtime/proc.go:203 +0x21e fp=0xc0007c9fe0 sp=0xc0007c9f60 pc=0x42f5de
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0007c9fe8 sp=0xc0007c9fe0 pc=0x45a511
# github.com/ethereum/go-ethereum/cmd/geth
/home/ia/go1.13.5.linux-amd64/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
collect2: error: ld returned 1 exit status

util.go:45: exit status 2
exit status 1
Makefile:21: recipe for target 'all' failed

```

Though `./build/bin/geth` still works.

**Comment by meowsbits** [comment]
Resolved.
